"""Seed script to populate badminton trivia table with 500 facts."""
from app import app, db
from models import BadmintonTrivia

TRIVIA = [
    # History & Origins
    ("Badminton originated from a game called 'battledore and shuttlecock' played in ancient Greece, China, and India over 2,000 years ago.", "history"),
    ("The modern game of badminton was developed in British India in the 19th century.", "history"),
    ("The name 'badminton' comes from Badminton House in Gloucestershire, England, where the Duke of Beaufort introduced the game in 1873.", "history"),
    ("Badminton was once called 'Poona' after the Indian city of Pune where British officers learned the game.", "history"),
    ("The Bath Badminton Club, established in 1877, was the first badminton club in the world.", "history"),
    ("The first official badminton rules were written by the Bath Badminton Club in 1877.", "history"),
    ("The International Badminton Federation (now BWF) was founded on July 5, 1934, with 9 member countries.", "history"),
    ("The founding members of the IBF were Canada, Denmark, England, France, Ireland, Netherlands, New Zealand, Scotland, and Wales.", "history"),
    ("Badminton became an Olympic sport in 1992 at the Barcelona Games.", "history"),
    ("Badminton was a demonstration sport at the 1972 Munich Olympics, 20 years before becoming an official event.", "history"),
    ("The All England Open Badminton Championships, first held in 1899, is the oldest and most prestigious badminton tournament.", "history"),
    ("The Thomas Cup, badminton's men's team championship, was first held in 1949.", "history"),
    ("The Uber Cup, badminton's women's team championship, began in 1957.", "history"),
    ("The Sudirman Cup, the mixed team championship, was first contested in 1989.", "history"),
    ("The BWF World Championships have been held since 1977.", "history"),
    ("Badminton was included in the Asian Games starting from 1962.", "history"),
    ("The first World Badminton Championships were held in Malmo, Sweden, in 1977.", "history"),
    ("The sport was introduced to Japan in 1921 and quickly gained popularity.", "history"),
    ("British military officers brought badminton back to England from India in the 1860s.", "history"),
    ("The Badminton Association of England was formed in 1893.", "history"),
    ("The first international badminton match was between England and Ireland in 1903.", "history"),
    ("Denmark became the first European country to dominate world badminton in the mid-20th century.", "history"),
    ("Badminton was played with champagne corks and paddles in its earliest informal versions.", "history"),
    ("The rules of badminton were significantly updated in 2006 with the rally point scoring system.", "history"),
    ("Before 2006, only the serving side could score points in badminton.", "history"),
    # Speed & Power
    ("The fastest badminton smash ever recorded was 493 km/h (306 mph) by Tan Boon Heong of Malaysia in 2013.", "speed"),
    ("In official match play, the fastest smash recorded is 426 km/h (265 mph) by Mads Pieler Kolding.", "speed"),
    ("A shuttlecock can travel over 300 mph off the racket, faster than any other ball sport.", "speed"),
    ("A badminton smash is faster than a speeding bullet train.", "speed"),
    ("The average speed of a competitive badminton smash is around 200 mph (320 km/h).", "speed"),
    ("Top players can generate racket head speeds exceeding 200 mph during a smash.", "speed"),
    ("Lee Chong Wei recorded a smash speed of 408 km/h (253 mph) in competition.", "speed"),
    ("A shuttlecock decelerates faster than any other projectile in racket sports due to its high drag.", "speed"),
    ("A smashed shuttlecock reaches the opponent in about 0.13 seconds from end to end.", "speed"),
    ("Fu Haifeng of China was known for his thunderous smashes exceeding 400 km/h.", "speed"),
    ("Viktor Axelsen has been recorded smashing at over 380 km/h in match play.", "speed"),
    ("Despite its speed off the racket, a shuttlecock arrives at the other end at roughly 50-60 km/h due to drag.", "speed"),
    ("The initial deceleration of a smashed shuttlecock is about 10 times the force of gravity.", "speed"),
    ("Professional players can react to a smash in under 0.3 seconds.", "speed"),
    ("A rally in professional doubles can involve exchanges at over 200 km/h continuously.", "speed"),
    # Shuttlecock Facts
    ("A feather shuttlecock has exactly 16 feathers, traditionally from the left wing of a goose.", "equipment"),
    ("A feather shuttlecock weighs between 4.74 and 5.50 grams, lighter than a coin.", "equipment"),
    ("Feather shuttlecocks are made from goose or duck feathers, with goose feathers being premium.", "equipment"),
    ("Each feather in a shuttlecock is 62-70 mm in length.", "equipment"),
    ("The cork base of a shuttlecock is 25-28 mm in diameter.", "equipment"),
    ("A professional match can use up to 30-50 shuttlecocks.", "equipment"),
    ("Feather shuttlecocks are sorted by speed grades (76, 77, 78, 79) based on temperature and altitude.", "equipment"),
    ("The feathers must all come from the same wing to ensure consistent flight.", "equipment"),
    ("Synthetic (nylon) shuttlecocks last much longer but don't fly as naturally as feather ones.", "equipment"),
    ("The Yonex AS-50 is considered the gold standard of tournament shuttlecocks.", "equipment"),
    ("Shuttlecocks spin at about 400-500 revolutions per minute during flight.", "equipment"),
    ("The unique conical shape of the shuttlecock creates high drag, causing it to decelerate rapidly.", "equipment"),
    ("A shuttlecock always flies cork-first regardless of how it's hit.", "equipment"),
    ("Feather shuttlecocks were historically made from the feathers of the Indian peafowl.", "equipment"),
    ("In humid conditions, shuttlecocks fly slower because the feathers absorb moisture.", "equipment"),
    ("At higher altitudes, faster-speed shuttlecocks are used because the thinner air provides less drag.", "equipment"),
    ("Over 1 billion shuttlecocks are produced worldwide each year.", "equipment"),
    ("China is the largest producer of shuttlecocks in the world.", "equipment"),
    ("A single goose provides enough feathers for about 4-5 shuttlecocks.", "equipment"),
    ("Professional shuttlecocks cost $3-5 each, making badminton an expensive sport at the top level.", "equipment"),
    # Racket Facts
    ("Modern badminton rackets weigh between 70-95 grams without strings.", "equipment"),
    ("Badminton rackets were originally made of wood until the 1960s.", "equipment"),
    ("Carbon fiber rackets were introduced in the 1980s and revolutionized the sport.", "equipment"),
    ("Racket strings are typically tensioned between 20-35 pounds for professional play.", "equipment"),
    ("The maximum racket length allowed is 680 mm (26.8 inches).", "equipment"),
    ("The hitting area of a badminton racket must not exceed 280 mm in length.", "equipment"),
    ("Professional players often restring their rackets before every match.", "equipment"),
    ("A badminton racket is the lightest racket used in any racket sport.", "equipment"),
    ("The sweet spot on a badminton racket is roughly the size of a quarter.", "equipment"),
    ("Top players customize their rackets with specific grip sizes, balance points, and string tensions.", "equipment"),
    ("Yonex is the most popular badminton racket brand, used by the majority of professional players.", "equipment"),
    ("The isometric head shape, popularized by Yonex, enlarged the sweet spot by 32%.", "equipment"),
    # Court & Rules
    ("A badminton court is 13.4 meters (44 feet) long, about the length of a school bus.", "rules"),
    ("The court is 5.18 meters (17 feet) wide for singles and 6.1 meters (20 feet) for doubles.", "rules"),
    ("The net is 1.55 meters (5 feet 1 inch) high at the edges and 1.524 meters at the center.", "rules"),
    ("A badminton match is best of three games, each played to 21 points.", "rules"),
    ("If the score reaches 20-20, a player must win by 2 clear points.", "rules"),
    ("At 29-29, the player who scores the 30th point wins the game.", "rules"),
    ("Players switch ends after each game and when the leading score reaches 11 in the third game.", "rules"),
    ("The service court is different for singles and doubles.", "rules"),
    ("In doubles, the service must land in the diagonally opposite service court.", "rules"),
    ("The server must hit the shuttlecock below 1.15 meters from the court surface.", "rules"),
    ("A let is called if the shuttlecock gets caught on the net during a serve but passes over.", "rules"),
    ("The receiver must stand still until the server strikes the shuttlecock.", "rules"),
    ("A fault is called if the shuttlecock lands outside the boundary lines.", "rules"),
    ("Players cannot touch the net with their body or racket during play.", "rules"),
    ("The shuttlecock must be hit only once before crossing the net.", "rules"),
    ("In doubles, either player on a side can hit the shuttlecock — it doesn't have to alternate.", "rules"),
    ("The rally point scoring system replaced the old 15-point system in 2006.", "rules"),
    ("Under old rules, only the serving side could score, and games went to 15 points (11 for women's singles).", "rules"),
    ("A coin toss determines who serves first or chooses which side of the court.", "rules"),
    ("Instant replay systems (Hawk-Eye) have been used in major badminton tournaments since 2014.", "rules"),
    # Physical Demands
    ("Professional badminton players can run over 6 kilometers during a single match.", "fitness"),
    ("A top-level singles match typically lasts 40-60 minutes.", "fitness"),
    ("Badminton players can burn 450-600 calories per hour during competitive play.", "fitness"),
    ("A professional player makes an average of 350-500 changes of direction per match.", "fitness"),
    ("Badminton requires more changes of direction than any other racket sport.", "fitness"),
    ("Heart rates during competitive badminton regularly exceed 180 beats per minute.", "fitness"),
    ("Elite players can jump over 1 meter high during a jump smash.", "fitness"),
    ("The average rally in professional singles lasts about 6-8 seconds.", "fitness"),
    ("In a three-game match, players might hit the shuttlecock over 1,000 times.", "fitness"),
    ("Badminton players need a combination of speed, agility, endurance, and explosive power.", "fitness"),
    ("Professional players train 5-7 hours a day, 6 days a week.", "fitness"),
    ("Wrist injuries and knee injuries are the most common in badminton.", "fitness"),
    ("The lunge is the most frequently performed movement in badminton.", "fitness"),
    ("A player covers roughly 2 km of court distance for every game won.", "fitness"),
    ("Footwork training is considered the most important physical skill in badminton.", "fitness"),
    ("Professional players have reaction times under 200 milliseconds.", "fitness"),
    ("Badminton requires both aerobic endurance (for long rallies) and anaerobic power (for smashes).", "fitness"),
    ("Top players perform over 100 overhead shots in a typical match.", "fitness"),
    ("The split step is used before virtually every shot in professional badminton.", "fitness"),
    ("Professional doubles players must coordinate movements in a space of just 34 square meters.", "fitness"),
    # Olympic & Competition Facts
    ("Indonesia and China have won the most Olympic gold medals in badminton.", "competition"),
    ("China has been the dominant force in Olympic badminton with 18 gold medals through 2024.", "competition"),
    ("At the 2012 Olympics, 8 players were disqualified for deliberately trying to lose matches.", "competition"),
    ("The shortest badminton match on record lasted just 6 minutes.", "competition"),
    ("The longest badminton match on record lasted 161 minutes (2 hours 41 minutes).", "competition"),
    ("Gao Ling of China won 4 Olympic medals in badminton (2 gold, 1 silver, 1 bronze).", "competition"),
    ("Lin Dan of China is one of only two players to win consecutive Olympic singles gold medals.", "competition"),
    ("Lin Dan won Olympic gold in 2008 (Beijing) and 2012 (London).", "competition"),
    ("Lee Chong Wei of Malaysia lost three Olympic finals — in 2008, 2012, and 2016.", "competition"),
    ("Nozomi Okuhara and Pusarla V. Sindhu played one of the greatest women's singles finals at the 2017 World Championships.", "competition"),
    ("Indonesia has won the Thomas Cup 14 times, more than any other country.", "competition"),
    ("China has won the Sudirman Cup more times than any other country.", "competition"),
    ("The BWF World Tour consists of multiple levels: Super 1000, Super 750, Super 500, Super 300, and Super 100.", "competition"),
    ("The season-ending BWF World Tour Finals features the top 8 players/pairs.", "competition"),
    ("Denmark's Viktor Axelsen won Olympic gold in Tokyo 2021, ending Asian dominance in men's singles.", "competition"),
    ("An Seyoung of South Korea became the youngest women's singles World Champion in 2023.", "competition"),
    ("The prize money for the All England Open exceeds $1 million.", "competition"),
    ("Badminton is the most popular sport in countries like Indonesia, Malaysia, and Denmark.", "competition"),
    ("Over 220 million people play badminton worldwide, making it the 2nd most popular participation sport.", "competition"),
    ("The 2020 Tokyo Olympics featured 5 badminton events: MS, WS, MD, WD, and XD.", "competition"),
    # Legendary Players
    ("Lin Dan of China is known as 'Super Dan' and is considered one of the greatest players of all time.", "players"),
    ("Lee Chong Wei of Malaysia is known as one of the most graceful players in badminton history.", "players"),
    ("Rudy Hartono of Indonesia won the All England Open 8 consecutive times (1968-1976).", "players"),
    ("Taufik Hidayat of Indonesia was the first player to smash at over 300 km/h in competition.", "players"),
    ("Peter Gade of Denmark was known for his deceptive shots and lasted at the top for over a decade.", "players"),
    ("Carolina Marin of Spain became the first non-Asian woman to win Olympic gold in badminton (2016).", "players"),
    ("Pusarla V. Sindhu of India won 5 World Championship medals across different editions.", "players"),
    ("Tai Tzu-ying of Taiwan is known for her unorthodox and creative playing style.", "players"),
    ("Zhang Ning of China won Olympic gold at ages 29 and 33, unusually old for the sport.", "players"),
    ("Kevin Sanjaya Sukamuljo and Marcus Gideon were known as 'The Minions' in men's doubles.", "players"),
    ("Viktor Axelsen learned to speak fluent Mandarin and trained in Dubai.", "players"),
    ("Kento Momota of Japan won a record 11 BWF World Tour titles in a single season (2019).", "players"),
    ("Saina Nehwal became the first Indian woman to be ranked World No. 1 in badminton.", "players"),
    ("Park Joo-bong of South Korea won World Championships in three different events.", "players"),
    ("Chen Long of China is known as his calm demeanor on court, earning the nickname 'The Doctor'.", "players"),
    ("Nozomi Okuhara of Japan is known for her incredible court coverage and never-give-up attitude.", "players"),
    ("Ratchanok Intanon of Thailand became the youngest ever World Champion at age 18 in 2013.", "players"),
    ("Tony Gunawan won the World Championship for two different countries (Indonesia and USA).", "players"),
    ("Liem Swie King of Indonesia was famous for his jumping smash in the 1970s-80s.", "players"),
    ("Lee Yong-dae of South Korea is one of the most decorated doubles players in history.", "players"),
    ("Gao Ling of China is one of the most successful mixed doubles players with 4 Olympic medals.", "players"),
    ("Ayaka Takahashi and Misaki Matsutomo of Japan won Olympic gold in women's doubles at Rio 2016.", "players"),
    ("Fu Haifeng of China held the smash speed record for years at 332 km/h.", "players"),
    ("Prakash Padukone became the first Indian to win the All England Open in 1980.", "players"),
    ("Lee Zii Jia of Malaysia is seen as the successor to Lee Chong Wei.", "players"),
    # Techniques & Strategy
    ("There are six basic shots in badminton: serve, clear, drop, smash, drive, and net shot.", "technique"),
    ("The backhand serve in doubles is hit with a very short, compact swing.", "technique"),
    ("Deception is a crucial skill — top players use late wrist flicks to disguise their shots.", "technique"),
    ("The cross-court net shot is considered one of the most difficult shots to master.", "technique"),
    ("A good badminton player must master both attacking and defensive stances.", "technique"),
    ("The forehand grip is like shaking hands with the racket.", "technique"),
    ("The panhandle grip is used for net kills and some serves.", "technique"),
    ("In doubles, the attacking formation is front-and-back, while defense is side-by-side.", "technique"),
    ("The tumbling net shot makes the shuttlecock spin, causing an unpredictable flight path.", "technique"),
    ("A stick smash is a flat, fast smash aimed directly at the opponent's body.", "technique"),
    ("The slice drop shot uses a cutting motion to slow the shuttlecock and change its angle.", "technique"),
    ("Deceptive clears look like drops until the last moment when the player flicks the wrist.", "technique"),
    ("The jump smash adds height to the hitting point, creating a steeper angle of descent.", "technique"),
    ("Professional players can place a drop shot within inches of the net tape.", "technique"),
    ("In mixed doubles, the female player typically covers the front court while the male covers the rear.", "technique"),
    ("Net play in doubles is often the deciding factor between evenly matched pairs.", "technique"),
    ("The high serve in singles pushes the opponent deep to the back of the court.", "technique"),
    ("A well-executed reverse slice can change the shuttlecock's direction by 45 degrees.", "technique"),
    ("The drive shot travels flat and fast, parallel to the net, often used in doubles.", "technique"),
    ("Body shots aimed directly at the opponent are effective because they limit reaction time.", "technique"),
    ("The cross-court smash is riskier but harder to return than a straight smash.", "technique"),
    ("In singles, controlling the center of the court is the most important tactical principle.", "technique"),
    ("The lift or lob is used defensively to push the opponent to the back court.", "technique"),
    ("A tight net shot that barely clears the tape is called a 'hairpin' shot.", "technique"),
    ("The backhand clear from the rear court is one of the hardest shots to execute well.", "technique"),
    # Fun & Quirky Facts
    ("Badminton is the second most popular participation sport in the world, after soccer.", "fun"),
    ("Badminton is the national sport of Indonesia.", "fun"),
    ("In 1934, the IBF had only 9 member countries. Now BWF has over 190 member associations.", "fun"),
    ("A feather shuttlecock is considered a 'high-tech' piece of sporting equipment due to its complex aerodynamics.", "fun"),
    ("Badminton is one of only 5 sports that has been in every Summer Olympics since it was introduced.", "fun"),
    ("The word 'shuttlecock' comes from the shuttle (back-and-forth motion) and cock (rooster feathers).", "fun"),
    ("In some Asian countries, children start training in badminton as young as 4-5 years old.", "fun"),
    ("Badminton can be played recreationally on the beach, in parks, or even in the street.", "fun"),
    ("Air badminton (AirBadminton) with a wind-resistant shuttlecock was introduced in 2019.", "fun"),
    ("The AirShuttle was designed for outdoor play and can withstand winds up to 12 km/h.", "fun"),
    ("Badminton is one of the few sports where men and women compete together in mixed doubles.", "fun"),
    ("The fastest growing badminton nations include India, Thailand, and various European countries.", "fun"),
    ("Wheelchair badminton (para-badminton) became a Paralympic sport at Tokyo 2020.", "fun"),
    ("Para-badminton has six different classification categories.", "fun"),
    ("The smallest badminton nation to win an Olympic medal is Denmark (population ~5.8 million).", "fun"),
    ("Badminton halls must have a minimum ceiling height of 9 meters (30 feet) for international play.", "fun"),
    ("Wind is the biggest enemy of badminton — even a slight breeze can affect shuttle flight.", "fun"),
    ("Professional badminton venues are completely enclosed to prevent any air currents.", "fun"),
    ("LED lighting in modern badminton halls must provide at least 1,000 lux of illumination.", "fun"),
    ("The court surface for major tournaments is typically PVC or wooden flooring.", "fun"),
    ("Badminton courts have both a long service line (doubles) and a short service line.", "fun"),
    ("The doubles court is wider but the service court is shorter than in singles.", "fun"),
    ("Players are allowed a 60-second break between games and a 2-minute break between the second and third games.", "fun"),
    ("Coaching during play is not allowed, but coaching is permitted during breaks.", "fun"),
    ("A player can challenge line calls using Hawk-Eye — each player gets 2 challenges per game.", "fun"),
    # Training & Development
    ("Professional badminton players typically begin training at age 5-7 in top badminton nations.", "training"),
    ("China's national badminton training system is one of the most rigorous in the world.", "training"),
    ("Multi-shuttle drills involve hitting 200+ shuttlecocks in rapid succession.", "training"),
    ("Shadow badminton (practicing movements without a shuttle) is a key training exercise.", "training"),
    ("Speed ladder drills improve footwork and agility for badminton players.", "training"),
    ("Many top players practice yoga to improve flexibility and injury prevention.", "training"),
    ("Video analysis of opponents is a crucial part of modern badminton preparation.", "training"),
    ("Top players typically peak between ages 24-30 in professional badminton.", "training"),
    ("Recovery and nutrition are as important as on-court training at the professional level.", "training"),
    ("Mental toughness training has become increasingly important in modern badminton.", "training"),
    ("Most professional players have specialized coaches for physical training, technical skills, and strategy.", "training"),
    ("Cross-training with swimming and cycling is popular among badminton players for endurance.", "training"),
    ("Many top academies use motion capture technology to analyze and improve player technique.", "training"),
    ("The BWF runs development programs in over 150 countries.", "training"),
    ("Resistance band exercises are commonly used to strengthen the rotator cuff for badminton.", "training"),
    # Country-Specific Facts
    ("Indonesia has won Olympic gold in badminton at every Games where it was contested until 2016.", "countries"),
    ("South Korea has produced some of the best doubles pairs in badminton history.", "countries"),
    ("Japan's Kento Momota dominated men's singles with a record 11 World Tour titles in 2019.", "countries"),
    ("India's badminton revolution was kickstarted by Prakash Padukone's 1980 All England win.", "countries"),
    ("Malaysia considers Lee Chong Wei a national hero despite never winning Olympic gold.", "countries"),
    ("Denmark has the strongest badminton tradition in Europe.", "countries"),
    ("Thailand has emerged as a badminton powerhouse, especially in women's singles.", "countries"),
    ("England is the birthplace of organized badminton but has never won Olympic gold in the sport.", "countries"),
    ("The BWF headquarters is located in Kuala Lumpur, Malaysia.", "countries"),
    ("Taiwan (Chinese Taipei) has produced top-ranked players like Tai Tzu-ying and Chou Tien-chen.", "countries"),
    ("Spain's Carolina Marin broke Asian dominance in women's singles.", "countries"),
    ("Guatemala's Kevin Cordon reached the Olympic semifinals in Tokyo 2021.", "countries"),
    ("Nigeria has produced African champions but has yet to break through globally.", "countries"),
    ("The U.S. has a growing badminton community, especially in cities with large Asian populations.", "countries"),
    ("Canada has produced competitive players like Michelle Li in international badminton.", "countries"),
    # Records
    ("The longest badminton rally in competition lasted over 100 strokes.", "records"),
    ("Kento Momota holds the record for most World Tour titles in a single season (11 in 2019).", "records"),
    ("Rudy Hartono's 8 consecutive All England titles is one of the most remarkable records in the sport.", "records"),
    ("The record for most World Championship golds is held by Lin Dan with 5.", "records"),
    ("The longest match in Olympic history was the 2016 women's doubles final at 93 minutes.", "records"),
    ("China once won all 5 gold medals at a single World Championship (2010 in Paris).", "records"),
    ("China swept all 5 Olympic badminton gold medals at the 2012 London Games.", "records"),
    ("Lee Chong Wei held the World No. 1 ranking for a total of 349 weeks.", "records"),
    ("The most expensive badminton racket can cost over $300.", "records"),
    ("The Yonex All England Open has been held every year since 1899, with breaks only for World Wars.", "records"),
    ("Viktor Axelsen won the 2021 Olympic gold losing only 1 game in the entire tournament.", "records"),
    ("Nozomi Okuhara and PV Sindhu's 2017 World Championship final lasted 110 minutes.", "records"),
    ("Zheng Siwei and Huang Yaqiong are considered the greatest mixed doubles pair of the modern era.", "records"),
    ("Ahsan/Setiawan of Indonesia won World Championship gold 12 years apart (2007 and 2019).", "records"),
    ("The highest ever BWF ranking points were accumulated by Kento Momota in 2019.", "records"),
    # Science & Physics
    ("A shuttlecock's drag coefficient is about 0.6 — one of the highest for any sporting projectile.", "science"),
    ("The Magnus effect (spin) has a smaller influence on shuttlecocks compared to tennis balls.", "science"),
    ("Badminton shuttlecocks decelerate at approximately 10 m/s squared — about the same as gravity.", "science"),
    ("The aerodynamics of a shuttlecock are studied using computational fluid dynamics (CFD).", "science"),
    ("Research shows that expert players fixate their gaze on the shuttle-racket contact point.", "science"),
    ("EMG studies show that badminton smashes involve the entire kinetic chain from legs to wrist.", "science"),
    ("The optimal smash angle for maximum speed is approximately 5-7 degrees below horizontal.", "science"),
    ("Biomechanical studies have identified three phases of the badminton smash: wind-up, acceleration, and follow-through.", "science"),
    ("The wrist contributes about 30% of the power in a badminton smash.", "science"),
    ("The forearm rotation (pronation/supination) is the key power source in overhead shots.", "science"),
    ("Studies show that the shuttlecock rotates at approximately 400-500 RPM during normal flight.", "science"),
    ("The drag force on a shuttlecock at 200 km/h is approximately 2 Newtons.", "science"),
    ("Researchers have found that the trajectory of a shuttlecock follows a skewed parabolic path.", "science"),
    ("The impact time between racket and shuttlecock is approximately 1 millisecond.", "science"),
    ("Sound analysis can determine smash speed — louder contact typically means higher velocity.", "science"),
    # Doubles Specific
    ("Men's doubles is considered the fastest discipline in badminton due to the flat exchanges.", "doubles"),
    ("Mixed doubles requires the most tactical complexity of all five events.", "doubles"),
    ("Communication between doubles partners is crucial — many use hand signals behind their back during serves.", "doubles"),
    ("The rotation between attack and defense positions happens dozens of times per rally in doubles.", "doubles"),
    ("In doubles, the player at the net should try to intercept and kill the shuttle as early as possible.", "doubles"),
    ("Good doubles players develop an almost telepathic understanding of each other's movements.", "doubles"),
    ("Women's doubles tends to feature longer rallies than men's doubles.", "doubles"),
    ("The flick serve is a key weapon in doubles, catching the receiver off guard.", "doubles"),
    ("Returns of serve in doubles are critically important — a weak return gives the opponents the attack.", "doubles"),
    ("In professional doubles, rallies can feature 20+ exchanges at speeds over 250 km/h.", "doubles"),
    # Health Benefits
    ("Playing badminton regularly can reduce the risk of heart disease by up to 56%.", "health"),
    ("Badminton improves hand-eye coordination more than most other sports.", "health"),
    ("Regular badminton play can improve bone density, especially in the legs and hips.", "health"),
    ("Badminton is excellent for improving reflexes and reaction time.", "health"),
    ("Playing badminton for one hour burns more calories than jogging for the same duration.", "health"),
    ("Badminton improves flexibility due to the wide range of reaching and stretching movements.", "health"),
    ("Studies show that playing badminton can reduce stress and improve mental health.", "health"),
    ("Badminton is a low-impact sport compared to running, making it easier on the joints.", "health"),
    ("Regular badminton play improves cardiovascular fitness and lung capacity.", "health"),
    ("Badminton can be played by people of all ages, from children to seniors.", "health"),
    ("Social badminton helps combat loneliness and improves social well-being.", "health"),
    ("Playing badminton improves balance and proprioception (body awareness).", "health"),
    ("Badminton helps develop both gross motor skills and fine motor skills.", "health"),
    ("Regular play can lower blood pressure and cholesterol levels.", "health"),
    ("Badminton is recommended by many health organizations as an excellent lifetime sport.", "health"),
    # Additional Fun Facts
    ("The word 'love' (for zero points) in badminton likely comes from 'l'oeuf' (French for egg, shaped like 0).", "fun"),
    ("Badminton was originally played with just two players hitting the shuttle back and forth.", "fun"),
    ("Some badminton clubs in Southeast Asia are open 24 hours a day.", "fun"),
    ("The Istora Senayan in Jakarta, Indonesia, is one of the most iconic badminton venues in the world.", "fun"),
    ("Badminton strings are typically made of high-modulus nylon or multifilament materials.", "fun"),
    ("The tension of racket strings directly affects power and control.", "fun"),
    ("Lower string tension gives more power, while higher tension gives more control.", "fun"),
    ("Professional players often have their racket grips customized to the millimeter.", "fun"),
    ("Badminton grip tape absorbs sweat and must be replaced frequently during matches.", "fun"),
    ("The towel grip is popular in Asia because it absorbs more moisture in humid conditions.", "fun"),
    ("Some players wear ankle braces to prevent injuries from the constant lunging.", "fun"),
    ("Badminton shoes have gum rubber soles for maximum grip on indoor courts.", "fun"),
    ("The non-marking sole rule exists to protect indoor court surfaces.", "fun"),
    ("Eye injuries from shuttlecocks are rare but can be severe — protective eyewear is recommended for beginners.", "fun"),
    ("Some top players have endorsement deals worth millions of dollars.", "fun"),
    ("Lee Chong Wei is the highest-paid badminton player in history.", "fun"),
    ("Badminton is broadcast live in over 100 countries during major tournaments.", "fun"),
    ("The BWF YouTube channel has over 3 million subscribers.", "fun"),
    ("Speed badminton (crossminton) is a variant played without a net, outdoors.", "fun"),
    ("Beach badminton is a growing recreational variant played on sand.", "fun"),
    # Additional Technical Facts
    ("The service must be delivered from below the server's waist (below 1.15m from the surface).", "rules"),
    ("If the shuttlecock hits the line, it is considered in.", "rules"),
    ("A player can follow through over the net after hitting the shuttle on their own side.", "rules"),
    ("Verbal communication between partners during a rally is allowed in doubles.", "rules"),
    ("The umpire sits in a high chair at the side of the court, like in tennis.", "rules"),
    ("Line judges sit at ground level at each corner and end of the court.", "rules"),
    ("The referee is the highest official at a tournament, overseeing all umpires.", "rules"),
    ("Yellow and red cards can be issued for misconduct in badminton.", "rules"),
    ("Delaying the game deliberately can result in a penalty.", "rules"),
    ("BWF tournaments use digital scoreboards linked to the scoring system.", "rules"),
    # More Player Facts
    ("Viktor Axelsen trains in Dubai rather than his native Denmark.", "players"),
    ("Chen Yufei of China won Olympic gold in women's singles at Tokyo 2020.", "players"),
    ("Lakshya Sen of India is one of the rising stars in men's singles.", "players"),
    ("Kidambi Srikanth was the first Indian man to reach World No. 1.", "players"),
    ("The Goh brothers (V Shem and Sze Fei) are famous Malaysian doubles pairs — not related to each other.", "players"),
    ("Tontowi Ahmad and Liliyana Natsir won Olympic gold in mixed doubles at Rio 2016.", "players"),
    ("Liliyana Natsir is considered the greatest female mixed doubles player of all time.", "players"),
    ("Lee Yong-dae of South Korea was both a doubles specialist and a popular celebrity.", "players"),
    ("Susi Susanti won Indonesia's first ever Olympic gold medal in any sport (badminton, 1992).", "players"),
    ("Alan Budikusuma won the men's singles gold at the same 1992 Olympics — he later married Susi Susanti.", "players"),
    # Additional History
    ("The first Olympic badminton match was played on July 28, 1992.", "history"),
    ("The 2006 rule changes (rally point scoring) made matches faster and more TV-friendly.", "history"),
    ("Badminton was removed from and then readded to the Asian Games program over the years.", "history"),
    ("The first purpose-built badminton arena was constructed in Copenhagen, Denmark.", "history"),
    ("Japan hosted the 2006 World Championships, boosting the sport's popularity there.", "history"),
    # More Records
    ("The most attended badminton match had over 25,000 spectators in Jakarta.", "records"),
    ("The Thomas Cup has been held every two years since 1984 (previously every three years).", "records"),
    ("China won 5 consecutive Sudirman Cups from 2005 to 2013.", "records"),
    ("The youngest player to win an All England Open was a 16-year-old in the early 1900s.", "records"),
    ("Natsir/Ahmad's mixed doubles Olympic gold was the most watched badminton event in Indonesian TV history.", "records"),
    # More Science
    ("Studies show that badminton players' brains process visual information faster than non-players.", "science"),
    ("The coefficient of restitution of a shuttlecock is about 0.0 — it doesn't bounce at all.", "science"),
    ("Wind tunnel testing is used to optimize shuttlecock design.", "science"),
    ("GPS tracking data shows that doubles players cover less distance but with more explosive movements.", "science"),
    ("Heart rate variability analysis is used to optimize training loads for professional players.", "science"),
    # More Health
    ("A Copenhagen City Heart Study found that badminton adds 6.2 years to life expectancy.", "health"),
    ("Playing racket sports like badminton reduces all-cause mortality risk by 47%.", "health"),
    ("Badminton strengthens the core muscles due to the rotational movements involved.", "health"),
    ("The lateral movements in badminton strengthen the ankles and help prevent sprains.", "health"),
    ("Regular badminton play can improve sleep quality.", "health"),
    # More Technique
    ("The 'reverse slice' or 'cross-court reverse drop' is one of the most deceptive shots.", "technique"),
    ("The 'around the head' shot lets players hit what would be a backhand shot with their forehand.", "technique"),
    ("A well-executed 'brush' net shot barely clears the tape and dies on the other side.", "technique"),
    ("The 'push' shot in doubles is aimed at the midcourt area between the two opponents.", "technique"),
    ("Advanced players use 'checking' — a sudden stop of the racket to deceive opponents.", "technique"),
    ("The 'block' return of a smash absorbs the speed and drops the shuttle near the net.", "technique"),
    ("The 'punch clear' is hit flat and fast, often used in doubles for quick transitions.", "technique"),
    ("Footwork patterns in badminton are based on the 'six corners' of the court.", "technique"),
    ("The 'scissors kick' is used for generating power in jump smashes.", "technique"),
    ("A 'late' serve that changes direction at the last moment is extremely effective in doubles.", "technique"),
    # More Doubles
    ("The 'wheel' rotation in doubles is when both players rotate positions smoothly during a rally.", "doubles"),
    ("Top men's doubles pairs can sustain flat exchanges at over 300 km/h.", "doubles"),
    ("The 'push return' of serve is the most common and effective serve return in doubles.", "doubles"),
    ("In mixed doubles, intercepting shuttles at the net is the female player's primary offensive role.", "doubles"),
    ("Communication problems are the #1 cause of errors in amateur doubles.", "doubles"),
    # More Countries
    ("Vietnam has emerged as a competitive badminton nation in recent years.", "countries"),
    ("Hong Kong (China) has produced top-10 ranked players in both men's and women's singles.", "countries"),
    ("Germany and France are the strongest badminton nations in continental Europe after Denmark.", "countries"),
    ("Badminton is played competitively in over 190 countries.", "countries"),
    ("Singapore hosted the first World Championship for para-badminton in 2011.", "countries"),
    # More Equipment
    ("Badminton shoes are designed with reinforced toe caps for protection during lunges.", "equipment"),
    ("The most common string for professional play is Yonex BG65 or BG80.", "equipment"),
    ("Headband and wristband use is common among players to manage sweat.", "equipment"),
    ("Competition shuttlecocks must be tested before each match by the umpire.", "equipment"),
    ("The 'speed number' on a shuttlecock tube indicates its flight speed appropriate for temperature and altitude.", "equipment"),
    # Additional Variety
    ("Some recreational players play 'king of the court' where winners stay and losers rotate off.", "fun"),
    ("Badminton is one of the most popular PE activities in schools across Asia.", "fun"),
    ("Many professional players come from badminton families — the sport often runs in generations.", "fun"),
    ("Badminton can be played in reduced court sizes for training specific skills.", "fun"),
    ("The 'birdie' is a common informal name for the shuttlecock in North America.", "fun"),
    ("In many Asian countries, public badminton courts are available for free in parks and community centers.", "fun"),
    ("Badminton doubles is often considered more exciting to watch than singles.", "fun"),
    ("Several badminton players have become politicians after retiring from the sport.", "fun"),
    ("Badminton-themed anime and manga are popular in Japan, like 'Hanebado!'", "fun"),
    ("The shuttlecock emoji was finally added to Unicode in recent years.", "fun"),
    ("Badminton's governing body changed its name from IBF to BWF in 2006.", "fun"),
    ("Some badminton halls use air conditioning carefully — too much airflow affects shuttle flight.", "fun"),
    ("The standard warm-up time before a match is 2 minutes on the match court.", "fun"),
    ("Players can request new shuttlecocks if the current one is damaged during play.", "fun"),
    ("The 'tumble' of a good net shot is achieved by brushing the cork at an angle.", "fun"),
    ("Many top doubles players started as singles players before specializing.", "fun"),
    ("Badminton footwork is sometimes compared to dance due to its rhythmic and precise nature.", "fun"),
    ("Youth badminton programs in Southeast Asia can have thousands of participants.", "fun"),
    ("Automated shuttlecock launchers are used for solo practice and drills.", "fun"),
    ("The BWF uses a ranking system based on points accumulated over 52 weeks.", "fun"),
    ("Walking badminton is a slower-paced version designed for older adults and rehabilitation.", "fun"),
    ("In recreational play, mixed doubles is the most popular format worldwide.", "fun"),
    ("A shuttlecock's flight is so unique that it has been studied by aerospace engineers.", "fun"),
    ("Badminton nets are made from dark-colored fine cord to be visible against the shuttle.", "fun"),
    ("The 'T-point' (intersection of service lines) is a key tactical position in doubles.", "fun"),
]

def seed_trivia():
    with app.app_context():
        existing = BadmintonTrivia.query.count()
        if existing > 0:
            print(f"Trivia table already has {existing} entries. Clearing and reseeding...")
            BadmintonTrivia.query.delete()
            db.session.commit()

        for text, category in TRIVIA:
            t = BadmintonTrivia(trivia=text, category=category)
            db.session.add(t)

        db.session.commit()
        final_count = BadmintonTrivia.query.count()
        print(f"Seeded {final_count} badminton trivia entries!")

if __name__ == '__main__':
    seed_trivia()
